# Generated by Django 4.1 on 2023-11-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros_proteccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='provicia',
            new_name='provincia',
        ),
    ]
